export const TERRAIN_CONFIG =
{
  BASE_HEIGHT: 40,
  NOISE_SCALE: 0.015,
  DETAIL_SCALE_MIN: 0.01,
  DETAIL_SCALE_RANGE: 0.025,
  CAVE_SCALE_MIN: 0.1,
  CAVE_SCALE_RANGE: 0.07,
  BIOME_SCALE: 0.005 * 10,
  DESERT_THRESHOLD: 0.3,
  SEA_LEVEL: 42,
  BEACH_MARGIN: 2,
  SURFACE_SOIL_DEPTH: 4,
  CAVE_MIN_DEPTH: 3,
  CAVE_DENSITY_THRESHOLD: 0.35,
  CAVE_MIN_Y: 5,
  LARGE_HILLS_AMPLITUDE: 35,
  SMALL_HILLS_AMPLITUDE: 4
};
